### PR TITLE
PHP8 Support

### PR DESCRIPTION
**Pull request by toooni**

### CODE REVIEW

**Comment by toooni** [comment]
@Alexandre-T Can you take a look at this PR?

**Comment by Alexandre-T** [comment]
@toooni , Sorry I can't because alexandre-t/doctrine2-spatial is a fork of creof/doctrine2-spatial.

I have worked a lot on these libraries but the creof team does not have the resources to merge my PR for a new version.

I am looking for a solution. I guess I'll create a new project from scratch and load this code inside. But, currently, I no longer have the time to do so. Next month, I have a project with doctrine2-spatial and symfony and PHP8.0.

**Comment by toooni** [comment]
Hi @Alexandre-T. Yes I know. I've targeted your fork because it's better maintained than `creof/doctrine2-spatial` and I was already using it before I've switched to PHP8. What's wrong with this fork? You can work with it like with a new project - but I guess this is up to you :)

**Comment by echantigny** [comment]
I am also looking into a solution to get this extension to work with php 8.  Any news on this front?  Is our only solution forking to update the php reqs?

**Comment by Alexandre-T** [comment]
Thanks for your PR. I checked it, you shouldn't remove compatibility with php7.2 without updating a major version. If another dev do a `composer update`, he won't be able to install it. (I know they should no more use php7.2, but they do :) )

I am about to port this project into my organization (which will easily allow to other members to participate), but I need to schedule it during two or three days to only work on this repository.

**Comment by toooni** [comment]
Yes. This change might be best suited in a major (2.1) update. But even without new major there shouldn't be any issues. The version will just not be installed when running `composer update` on PHP <= 7.2. The current (2.0.0) will still be working well.

**Comment by echantigny** [comment]
Just adding support for both > 7.2 and 8 would be enough to fix this issue.  I've been installing it with --ignore-platform-req php and I haven't ran into any issues.  There shouldn't be any features broken by 8 in there.

I would definitely like to update my composer packages without ignoring php's version.

**Comment by Alexandre-T** [comment]
OK @echantigny . Let's do it.

@toooni , please update the composer.json and let the compatibility with PHP7.2, then I will merge the pull request.

**Comment by toooni** [comment]
I've updated composer.json and readme. Since these changes are not introducing new features or anything I would have advised to not support PHP 7.2 anymore since it's EOL was last December. But this is up to you 👍

**Comment by Alexandre-T** [comment]
Thank you @toooni , I checked what is breaking. It seems to only be deprecations in PHPUnit, I merge the branch and first week of July, I will move all of this in a dedicated repository and I will create a new package which will replace this one.

**Comment by Alexandre-T** [comment]
I created an organization named [LongitudeOne](https://github.com/longitude-one) and a [new package](https://github.com/longitude-one/doctrine-spatial) that will replace and maintain this awesome spatial extension. All improvements from the PR I pushed 2 years ago are also included. I published a pre-released which is compatible with PHP8, MySQL5.7, MySQL8, PostgreSQL13 and PostGis 3.1.

It seems to work on my app, tests are done but I thank you for your feedbacks :)

I will archive this repository (If I can, I don't even know if I can archive a forked repo)

**Comment by toooni** [comment]
Awesome! Thank you @Alexandre-T! I've installed your RC in our application and everything seems to work fine.

**Comment by echantigny** [comment]
@Alexandre-T Installed it too and I'm not seeing any issues yet either. Merci!

**Comment by Alexandre-T** [comment]
Thank you for your feedback. The 3.0.0 will be output at the end of month.

**Pull request merged**
